/*================ */
/* SOLUCIÓN GUIA 6 */
/*================ */

/* Orden 1 */
CREATE TABLE PAIS (
   CODIGO               CHAR(3)              NOT NULL,
   NOMBRE               VARCHAR(30)          NOT NULL,
   CONSTRAINT PK_PAIS PRIMARY KEY (CODIGO)
);
CREATE TABLE LOCALIDAD (
   CODIGO               SMALLINT             NOT NULL,
   NOMBRE               VARCHAR(60)          NOT NULL,
   CODIGO_POSTAL        SMALLINT             NULL,
   CONSTRAINT PK_LOCALIDAD PRIMARY KEY (CODIGO)
);
CREATE TABLE TIPO_DOMICILIO (
   ID                   INTEGER              NOT NULL,
   TIPO                 SMALLINT             NOT NULL,
   NOMBRE               CHAR(60)             NOT NULL,
   CONSTRAINT PK_TIPO_DOMICILIO PRIMARY KEY (ID),
   CONSTRAINT UK_TIPODOMICILIO UNIQUE (TIPO)
);
CREATE TABLE FUNCION (
   ID                   INTEGER               NOT NULL,
   CODIGO               SMALLINT              NOT NULL,
   NOMBRE               VARCHAR(60)           NOT NULL,
   CONSTRAINT PK_FUNCION PRIMARY KEY (ID),
   CONSTRAINT UK_FUNCION UNIQUE (CODIGO)
);
CREATE TABLE TIPO_PERSONAJURIDICA (
   ID                   INTEGER                 NOT NULL,
   CODIGO               SMALLINT                 NOT NULL,
   NOMBRE               VARCHAR(60)             NOT NULL,
   CONSTRAINT PK_TIPO_PERSONAJURIDICA PRIMARY KEY (ID),
   CONSTRAINT UK_TIPO_PERSONAJURIDICA UNIQUE (CODIGO)
);


/* Orden 2 */
CREATE TABLE PERSONA (
   ID                   INTEGER             NOT NULL,
   CODIGO               INTEGER             NOT NULL,
   TELEFONO             CHAR(20)            NULL,
   TELEFONO_MOVIL       CHAR(20)            NULL,
   CORREO_ELECTRONICO   CHAR(120)           NULL,
   CODIGO_PAIS          CHAR(3)             NULL,
   CONSTRAINT PK_PERSONA PRIMARY KEY (ID),
   CONSTRAINT UK_PERSONA UNIQUE (codigo),
   CONSTRAINT FK_PERSONA_PAIS FOREIGN KEY (CODIGO_PAIS)
      REFERENCES PAIS (CODIGO)
);

/* Orden 3 */
CREATE TABLE DOMICILIO (
   ID                   INTEGER              NOT NULL,
   ID_PERSONA           INTEGER              NOT NULL,
   ITEM                 SMALLINT             NOT NULL,
   DETALLE_DOMICILIO    CHAR(100)            NOT NULL,
   CODIGO_LOCALIDAD     SMALLINT              NOT NULL,
   ID_TIPODOMICILIO     INTEGER              NULL,
   CONSTRAINT PK_DOMICILIO PRIMARY KEY (ID),
   CONSTRAINT UK_DOMICILIO UNIQUE (ID_PERSONA, ITEM),
   CONSTRAINT FK_DOMICILIO_LOCALIDAD FOREIGN KEY (CODIGO_LOCALIDAD)
     REFERENCES LOCALIDAD (CODIGO),
   CONSTRAINT FK_DOMICILIO_PERSONA FOREIGN KEY (ID_PERSONA)
      REFERENCES PERSONA (ID),
   CONSTRAINT FK_DOMICILI_TIPO_DOM FOREIGN KEY (ID_TIPODOMICILIO)
      REFERENCES TIPO_DOMICILIO (ID)
);

CREATE TABLE PERSONA_JURIDICA (
   ID                   INTEGER              NOT NULL,
   CUIT1                smallint             NULL,
   CUIT2		INTEGER			NULL,
   CUIT3		smallint		Null,
   RAZON_SOCIAL         VARCHAR(40)          NOT NULL,
   NOMBRE_FANTASIA      VARCHAR(40)          NOT NULL,
   ID_PERSONA           INTEGER              NOT NULL,
   ID_TIPOPERSONAJURIDICA INTEGER            NULL,
   CONSTRAINT PK_PERSONA_JURIDICA PRIMARY KEY (ID),
      CONSTRAINT UK_PERSONA_JURIDICA UNIQUE (CUIT1,CUIT2,CUIT3),
   CONSTRAINT FK_PERSONA_JURIDICA_PERSONA FOREIGN KEY (ID_PERSONA)
      REFERENCES PERSONA (ID),
   CONSTRAINT FK_PERSONA_JURIDIDA_TIPO_PERSONA FOREIGN KEY (ID_TIPOPERSONAJURIDICA)
      REFERENCES TIPO_PERSONAJURIDICA (ID)
);

CREATE TABLE PERSONA_FISICA (
   ID                   INTEGER                 NOT NULL,
   TIPO_DOCUMENTO       CHAR(1)              NOT NULL,
   NUMERO_DOCUMENTO     INTEGER                 NOT NULL,
   APELLIDO             VARCHAR(80)             NOT NULL,
   NOMBRE               VARCHAR(80)             NOT NULL,
   SEXO                 CHAR(1)              NOT NULL,
   FECHA_NACIMIENTO     DATE                 NULL,
   OBSERVACIONES        VARCHAR(200)           NULL,
   ID_PERSONA           INTEGER                 NULL,
   CONSTRAINT PK_PERSONA_FISICA PRIMARY KEY (ID),
   CONSTRAINT UK_PERSONA_FISICA UNIQUE (TIPO_DOCUMENTO, NUMERO_DOCUMENTO),
   CONSTRAINT FK_PERSONA__FK_PERSON_PERSONA FOREIGN KEY (ID_PERSONA)
      REFERENCES PERSONA (ID)
);

CREATE TABLE INTEGRA_PERSONA_JURIDICA (
   ID                   INTEGER                 NOT NULL,
   ID_PERSONA_JURIDICA  INTEGER                 NOT NULL,
   ITEM                 SMALLINT                 NOT NULL,
   ID_PERSONA_FISICA    INTEGER                 NOT NULL,
   ID_FUNCION           INTEGER                 NOT NULL,
   OBSERVACIONES        CHAR(100)            NOT NULL,
   CONSTRAINT PK_INTEGRA_PERSONA_JURIDICA PRIMARY KEY (ID),
   CONSTRAINT UK_INTEGRA_PERSONA_JURIDICA UNIQUE (ID_PERSONA_JURIDICA, ITEM),
   CONSTRAINT FK_INTEGRA_PERSONA_FUNCION FOREIGN KEY (ID_FUNCION)
      REFERENCES FUNCION (ID),
   CONSTRAINT FK_INTEGRA_PERSONA_PF FOREIGN KEY (ID_PERSONA_FISICA)
      REFERENCES PERSONA_FISICA (ID),
	  CONSTRAINT FK_INTEGRA_PERSONA_PJ FOREIGN KEY (ID_PERSONA_JURIDICA)
      REFERENCES PERSONA_JURIDICA (ID)
	  
);





