/*==============================================================*/
/* GUIA DE PRÁCTICA 5                                           */
/*==============================================================*/

/* Tablas de orden 1 */
CREATE TABLE PROVINCIA (
   ID_PROVINCIA         SMALLINT                NOT NULL,
   NOM_PROVINCIA        VARCHAR(30)             NOT NULL,
   CONSTRAINT PK_PROVINCIA PRIMARY KEY (ID_PROVINCIA)
);
CREATE TABLE SECCION (
   ID_SECCION           SMALLINT                NOT NULL,
   NOM_SECCION          VARCHAR(30)             NOT NULL,
   CONSTRAINT PK_SECCION PRIMARY KEY (ID_SECCION)
);
CREATE TABLE CARGO (
   ID_CARGO             SMALLINT                NOT NULL,
   NOM_CARGO            VARCHAR(30)             NOT NULL,
   CONSTRAINT PK_CARGO PRIMARY KEY (ID_CARGO)
);
CREATE TABLE ESPECIALIDAD (
   ID_ESPECIALIDAD      SMALLINT                NOT NULL,
   NOM_ESPECIALIDAD     VARCHAR(40)             NOT NULL,
   CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY (ID_ESPECIALIDAD)
);

/* Tablas de orden 2 */

CREATE TABLE LOCALIDAD (
   ID_PROVINCIA         SMALLINT                NOT NULL,
   ID_LOCALIDAD         SMALLINT                NOT NULL,
   NOM_LOCALIDAD        VARCHAR(40)             NOT NULL,
   CONSTRAINT PK_LOCALIDAD PRIMARY KEY (ID_PROVINCIA, ID_LOCALIDAD),
   CONSTRAINT FK_LOCALIDAD_PROVINCIA FOREIGN KEY (ID_PROVINCIA)
      REFERENCES PROVINCIA (ID_PROVINCIA)
);

CREATE TABLE SECTOR (
   ID_SECCION           SMALLINT                NOT NULL,
   ID_SECTOR            SMALLINT                NOT NULL,
   NOM_SECTOR           VARCHAR(30)             NOT NULL,
   CONSTRAINT PK_SECTOR PRIMARY KEY (ID_SECCION, ID_SECTOR),
   CONSTRAINT FK_SECTOR_SECCION FOREIGN KEY (ID_SECCION)
      REFERENCES SECCION (ID_SECCION)
);

/* Tablas de orden 3 */
CREATE TABLE PERSONA (
   TIPODOC              VARCHAR(10)             NOT NULL DEFAULT 'DNI' CHECK (TIPODOC IN ('DNI','LC','PASAPORTE','OTRO')),
   NRODOC               INTEGER                 NOT NULL,
   SEXO                 VARCHAR(1)              NOT NULL,
   D_PROVINCIA_V        SMALLINT                NOT NULL,
   ID_LOCALIDAD_V       SMALLINT                NOT NULL,
   ID_PROVINCIA_N       SMALLINT                NULL,
   ID_LOCALIDAD_N       SMALLINT                NULL,
   TIPODOC_P           VARCHAR(10)              NULL,
   NRODOC_P             INTEGER                 NULL,
   SEXO_P               VARCHAR(1)              NULL,
   TIPODOC_M            VARCHAR(10)              NULL,
   NRODOC_M             INTEGER                 NULL,
   SEXO_M               VARCHAR(1)              NULL,
   APENOM               VARCHAR(40)             NOT NULL,
   DOMICILIO            VARCHAR(50)             NULL,
   FENACI               DATE                    NULL,
   CONSTRAINT PK_PERSONA PRIMARY KEY (TIPODOC, NRODOC, SEXO),
   CONSTRAINT FK_PERSONA_LOCALIDAD_NAC FOREIGN KEY (ID_PROVINCIA_N, ID_LOCALIDAD_N)
      REFERENCES LOCALIDAD (ID_PROVINCIA, ID_LOCALIDAD),
	CONSTRAINT FK_PERSONA_PADRE FOREIGN KEY (TIPODOC_P, NRODOC_P, SEXO_P)
      REFERENCES PERSONA (TIPODOC, NRODOC, SEXO),
	CONSTRAINT FK_PERSONA_MADRE FOREIGN KEY (TIPODOC_M, NRODOC_M, SEXO_M)
      REFERENCES PERSONA (TIPODOC, NRODOC, SEXO),
	CONSTRAINT FK_PERSONA_FK4_LOCALIDAD_VIVE FOREIGN KEY (D_PROVINCIA_V, ID_LOCALIDAD_V)
      REFERENCES LOCALIDAD (ID_PROVINCIA, ID_LOCALIDAD)
);

/* ***************************************************************************************  */
/* Las FK de persona --> persona fueron creadas en la misma instrucción CREATE             */
/* Otra alternativa es, tal como se indico en clase, generarlas con una instruccion aparte */ 
/* A modo de ejemplo, se rompen (drop) y vuelven a crear:                                   */
/* ***************************************************************************************  */
ALTER TABLE PERSONA DROP CONSTRAINT FK_PERSONA_PADRE;
ALTER TABLE PERSONA DROP CONSTRAINT FK_PERSONA_MADRE;

ALTER TABLE PERSONA ADD CONSTRAINT FK_PERSONA_PADRE FOREIGN KEY (TIPODOC_P, NRODOC_P, SEXO_P)
      REFERENCES PERSONA (TIPODOC, NRODOC, SEXO);
ALTER TABLE PERSONA ADD CONSTRAINT FK_PERSONA_mADRE FOREIGN KEY (TIPODOC_M, NRODOC_M, SEXO_M)
      REFERENCES PERSONA (TIPODOC, NRODOC, SEXO);



/* Tablas de orden 4 */	  
CREATE TABLE EMPLEADO (
   ID_EMPLEADO          INTEGER                 NOT NULL,
   TIPODOC              VARCHAR(10)              NOT NULL,
   NRODOC               INTEGER                 NOT NULL,
   SEXO                 VARCHAR(1)              NOT NULL,
   FEINGRESO            DATE                    NOT NULL,
   CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO),
   CONSTRAINT FK_EMPLEADO_PERSONA FOREIGN KEY (TIPODOC, NRODOC, SEXO)
      REFERENCES PERSONA (TIPODOC, NRODOC, SEXO)
);
CREATE TABLE MEDICO (
   MATRICULA            SMALLINT                NOT NULL,
   ID_ESPECIALIDAD      SMALLINT                NOT NULL,
   TIPODOC              VARCHAR(10)              NOT NULL,
   NRODOC               INTEGER                 NOT NULL,
   SEXO                 VARCHAR(1)              NOT NULL,
   CONSTRAINT PK_MEDICO PRIMARY KEY (MATRICULA),
   CONSTRAINT FK_MEDICO_FK1Y_ESPECIAL FOREIGN KEY (ID_ESPECIALIDAD)
      REFERENCES ESPECIALIDAD (ID_ESPECIALIDAD),
	   CONSTRAINT FK_MEDICO_FK2Y_PERSONA FOREIGN KEY (TIPODOC, NRODOC, SEXO)
      REFERENCES PERSONA (TIPODOC, NRODOC, SEXO)
);
  

/* Tablas de orden 5 */	  
	  
CREATE TABLE SALA (
   ID_SECCION           SMALLINT                NOT NULL,
   ID_SECTOR            SMALLINT                NOT NULL,
   NRO_SALA             SMALLINT                NOT NULL,
   ID_ESPECIALIDAD      SMALLINT                NOT NULL,
   ID_EMPLEADO          INTEGER                 NOT NULL,
   NOM_SALA             VARCHAR(30)             NULL,
   CAPACIDAD            SMALLINT                NULL,
   CONSTRAINT PK_SALA PRIMARY KEY (ID_SECCION, ID_SECTOR, NRO_SALA),
   CONSTRAINT FK_SALA_SECTOR FOREIGN KEY (ID_SECCION, ID_SECTOR)
      REFERENCES SECTOR (ID_SECCION, ID_SECTOR),
   CONSTRAINT FK_SALA_EMPLEADO FOREIGN KEY (ID_EMPLEADO)
      REFERENCES EMPLEADO (ID_EMPLEADO),
	CONSTRAINT FK_SALA_ESPECIALIDAD FOREIGN KEY (ID_ESPECIALIDAD)
      REFERENCES ESPECIALIDAD (ID_ESPECIALIDAD)
);

/* Tablas de orden 6 */
CREATE TABLE ASIGNACION (
   ID_ASIGNACION        INTEGER                 NOT NULL,
   MATRICULA            SMALLINT                NOT NULL,
   TIPODOC              VARCHAR(10)              NOT NULL,
   NRODOC               INTEGER                 NOT NULL,
   SEXO                 VARCHAR(1)              NOT NULL,
   ID_SECCION           SMALLINT                NOT NULL,
   ID_SECTOR            SMALLINT                NOT NULL,
   NRO_SALA             SMALLINT                NOT NULL,
   ID_EMPLEADO          INTEGER                 NOT NULL,
   FEASIGNA             DATE                    NOT NULL,
   FESALIDA             DATE                    NULL,
   CONSTRAINT PK_ASIGNACION PRIMARY KEY (ID_ASIGNACION),
   CONSTRAINT FK_ASIGNACION_PERSONA FOREIGN KEY (TIPODOC, NRODOC, SEXO)
      REFERENCES PERSONA (TIPODOC, NRODOC, SEXO),
	  CONSTRAINT FK_ASIGNACION_SALA FOREIGN KEY (ID_SECCION, ID_SECTOR, NRO_SALA)
      REFERENCES SALA (ID_SECCION, ID_SECTOR, NRO_SALA),
	  CONSTRAINT FK_ASIGNACION_EMPLEADO FOREIGN KEY (ID_EMPLEADO)
      REFERENCES EMPLEADO (ID_EMPLEADO),
	  CONSTRAINT FK_ASIGNACION_MEDICO FOREIGN KEY (MATRICULA)
      REFERENCES MEDICO (MATRICULA)
);

CREATE TABLE HISTORIAL (
   ID_EMPLEADO          INTEGER              NOT NULL,
   FECHAINICIO          DATE                 NOT NULL,
   ID_CARGO             SMALLINT             NOT NULL,
   FECHAFIN             DATE                 NULL,
   CONSTRAINT PK_HISTORIAL PRIMARY KEY (ID_EMPLEADO, FECHAINICIO),
   CONSTRAINT FK_HISTORIAL_CARGO FOREIGN KEY (ID_CARGO)
      REFERENCES CARGO (ID_CARGO),
   CONSTRAINT FK_HISTORIAL_EMPLEADO FOREIGN KEY (ID_EMPLEADO)
      REFERENCES EMPLEADO (ID_EMPLEADO)	  
);

CREATE TABLE TRABAJA_EN (
   ID_EMPLEADO          INTEGER              NOT NULL,
   ID_SECCION           SMALLINT             NOT NULL,
   ID_SECTOR            SMALLINT             NOT NULL,
   NRO_SALA             SMALLINT             NOT NULL,
   CONSTRAINT PK_TRABAJA_EN PRIMARY KEY (ID_SECCION, ID_SECTOR, ID_EMPLEADO, NRO_SALA),
   CONSTRAINT FK_TRABAJA_EMPLEADO FOREIGN KEY (ID_EMPLEADO)
      REFERENCES EMPLEADO (ID_EMPLEADO),
   CONSTRAINT FK_TRABAJA_SALA FOREIGN KEY (ID_SECCION, ID_SECTOR, NRO_SALA)
      REFERENCES SALA (ID_SECCION, ID_SECTOR, NRO_SALA)
);


